services:
  ollama:
    image: ollama/ollama:latest
    container_name: offline-prompt-ollama
    ports:
      - '11434:11434'
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_MODELS=/root/.ollama/models
      # Memory-optimized settings for Mac Mini M1
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_FLASH_ATTENTION=1
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'ollama', 'list']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M

volumes:
  ollama_data:
    driver: local
